# Generated by Django 3.2.8 on 2021-12-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.BooleanField(default=False),
        ),
    ]
