# Generated by Django 3.2.8 on 2021-12-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaDB', '0004_alter_usuarios_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='estado',
            field=models.CharField(choices=[('l', 'Libre'), ('o', 'Ocupado'), ('r', 'Reservado')], default='l', max_length=20),
        ),
    ]
