# Generated by Django 3.2.8 on 2021-12-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaDB', '0005_alter_prestamos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='estado',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Ocupado', 'Ocupado'), ('Reservado', 'Reservado')], default='Libre', max_length=20),
        ),
    ]
