# Generated by Django 3.2.8 on 2021-12-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaDB', '0006_alter_prestamos_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamos',
            old_name='fecha',
            new_name='fecha_prestamo',
        ),
        migrations.AddField(
            model_name='prestamos',
            name='fecha_entrega',
            field=models.DateField(null=True),
        ),
    ]
