# Generated by Django 3.2.8 on 2021-12-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaDB', '0007_auto_20211204_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='fecha_reserva',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='fecha_prestamo',
            field=models.DateField(null=True),
        ),
    ]
